### ISSUE TITLE
Error while fetching command metadata outside the project.

### ISSUE THREAD

**Issue by gastaldi** [rmpestano/swagger-addon#4]
Using the Forge shell, after you install the Swagger Forge addon, if you navigate to a project w/o a project, the following error is displayed in the logs: 

```
SEVERE: Error while getting command name for class org.jboss.swagger.addon.ui.SwaggerSetupCommand_$$_javassist_eb209e4f-adbd-4e0b-a21c-5c651ffe9f69
java.lang.IllegalStateException: A project is required in the current context
    at org.jboss.forge.addon.projects.ui.AbstractProjectCommand.getSelectedProject(AbstractProjectCommand.java:78)
    at org.jboss.swagger.addon.ui.SwaggerSetupCommand.getMetadata(SwaggerSetupCommand.java:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
    at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
    at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
    at org.jboss.swagger.addon.ui.SwaggerSetupCommand_$$_javassist_eb209e4f-adbd-4e0b-a21c-5c651ffe9f69.getMetadata(SwaggerSetupCommand_$$_javassist_eb209e4f-adbd-4e0b-a21c-5c651ffe9f69.java)
    at org.jboss.forge.addon.ui.impl.command.CommandFactoryImpl.getCommandName(CommandFactoryImpl.java:86)
    at org.jboss.forge.addon.ui.impl.command.CommandFactoryImpl.findCommand(CommandFactoryImpl.java:146)
    at org.jboss.forge.addon.ui.impl.command.CommandFactoryImpl.getNewCommandByName(CommandFactoryImpl.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
    at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
    at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
    at org.jboss.forge.addon.ui.impl.command.CommandFactoryImpl_$$_javassist_9642df0b-caf7-4fd5-b571-22d218ad198a.getNewCommandByName(CommandFactoryImpl_$$_javassist_9642df0b-caf7-4fd5-b571-22d218ad198a.java)
    at org.jboss.forge.addon.shell.aesh.ForgeCommandRegistry.findCommand(ForgeCommandRegistry.java:142)
    at org.jboss.forge.addon.shell.aesh.ForgeCommandRegistry.getForgeCommand(ForgeCommandRegistry.java:117)
    at org.jboss.forge.addon.shell.aesh.ForgeCommandRegistry.getCommand(ForgeCommandRegistry.java:91)
    at org.jboss.aesh.console.AeshConsoleImpl.getCommand(AeshConsoleImpl.java:247)
    at org.jboss.aesh.console.AeshConsoleImpl.access$100(AeshConsoleImpl.java:62)
    at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:308)
    at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

The solution is to not display the project name in this line: https://github.com/rmpestano/swagger-addon/blob/master/src/main/java/org/jboss/swagger/addon/ui/SwaggerSetupCommand.java#L53

**Comment by rmpestano** [comment]
I'll take a look. Maybe we can use isEnabled and display the command only if there is a project
