### ISSUE TITLE
Getting Exception in Swagger: Setup

### ISSUE THREAD

**Issue by subodh27** [rmpestano/swagger-addon#5]
**_ERROR**_ Error while executing 'Swagger: Setup'
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.j...:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
at org.jboss.swagger.addon.ui.SwaggerSetupCommand_$$_javassist_bb90bc04-b144-409f-a1e9-6223e21d35df.execute(SwaggerSetupCommand_$$_javassist_bb90bc04-b144-409f-...)
at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.execute(SingleCommandControllerImpl.ja...:94)
at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
at org.jboss.aesh.console.AeshPro...(AeshProcess.java:53)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/jboss/modules/ModuleClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/jboss/modules/ModuleClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:335)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
at org.jboss.swagger.addon.util.FileUtils.<clinit>(FileUtils.java:18)
at org.jboss.swagger.addon.ui.SwaggerSetupCommand.copySwaggerUIResources(SwaggerSetupCommand.java:99)
at org.jboss.swagger.addon.ui.SwaggerSetupCommand.execute(SwaggerSetupCommand.java:80)
... 16 more

**Comment by rmpestano** [comment]
Hi @subodh27, can you share your setup (ide and forge plugin version) ?

**Comment by subodh27** [comment]
IDE:
Red Hat JBoss Developer Studio
Version: 10.0.0.GA

Forge 3.2.2.Final - embedded

**Comment by chgangaraju** [comment]
+1

IDE: Intellij IDEA 2016.2
Installed Forge using forge-idea-plugin-1.1.17.Final.zip

**Comment by rmpestano** [comment]
Hi guys, just updated dependencies, can you try with latest changes? 

tested under idea 14.1.7 and forge plugin 1.1.17

**Comment by chgangaraju** [comment]
Thanks @rmpestano , Its working for me
